#Alexandra Pinedo
#ITP 116, 10:00-10:50a.m.
#Assignment 1 This program contains a mad libs story
playersName = input("Enter your name: ")
employerName = input("Enter the name of your employer: ")
numb = int(input("Enter a 4-digit integar:")
)
print("Hi " + playersName + " I work at " + employerName + " Do you know how many people work there? ", numb)
thing = input("Name a singular object: ")
print("I was there first employee so I get a " + thing + " ." + " As a reward of my loyalty. The CEO and I dormed in Marks Tower together.")
wordKite = int(input("Enter one number: ")
)
print("If I remember correctly we had", wordKite)
print("parking tickets in our names that still haven't been paid off and its been 35 years!")
deci = int(input("Enter float number here:")
)
print("In fact, we had a", deci)
print("chance if getting caught")
foodLocation = int("Enter a food location: ")
print("College days were my glory days, but eating at " + foodLocation)